version: '3.8'

services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: poetry run celery -A products_test worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: poetry run celery -A products_test beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

